services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joaovitor98/xpe-challenge-app
    container_name: app
    tty: true
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - challenge
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    networks:
      - challenge
    volumes:
      - /cache/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: joaovitor98/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - challenge
    tty: true
    restart: unless-stopped
    depends_on:
      - app

networks:
  challenge:
    driver: bridge
